spring.application.name=vitaltrack-api

spring.datasource.url=jdbc:postgresql://localhost:5432/vitaltrack
spring.datasource.username=jean

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
